# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "ddd"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "Simple HTML5 theme for http://gohugo.io/"
homepage = "http://diegomichel.org/ddd"
tags = ["", ""]
features = ["", ""]
min_version = 0.13

[author]
  name = "Diego Michel Rubio Ramirez"
  homepage = "http://diegomichel.org"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
